Repository libass/libass, pull requests merged in 2020-10, with the labels that each got.

#434 Fix Banner/Scroll effects & simplify clip coordinate conversion
  libass/ass_parse.c
  libass/ass_render.c
  libass/ass_render.h
Labels: compatibility, cosmetic

#439 ass_render: Replace Segment with Rect
  libass/ass_render.c
  libass/ass_render.h
Labels: cosmetic

#440 coretext: return full/PostScript name on fallback
  libass/ass_coretext.c
Labels: bug, fonts, macos
