Repository libass/libass, pull requests merged in 2024-06, with the labels that each got.

#768 Constify API parameters where possible
  libass/ass.c
  libass/ass.h
  libass/ass_library.c
Labels: api

#775 ass_utils: add ass_malloc and ass_free routines
  libass/Makefile_library.am
  libass/ass.h
  libass/ass_library.c
  libass/ass_types.h
  libass/libass.sym
Labels: api

#786 ass_shaper: check for singleton returns from harfbuzz; fixes #566
  libass/ass_shaper.c
Labels: shaper

#767 compare: add support for a wider PNG range
  compare/image.c
Labels: enhancement
