Repository libass/libass, pull requests merged in 2024-01, with the labels that each got.

#723 readme: replace erroneous pseudo spec
  README.md
Labels: doc

#683 directwrite: read metadata on our own, use DirectWrite-reported name as fallback
  libass/ass_directwrite.c
  libass/ass_directwrite_info_template.h
Labels: fonts, windows

#729 font: prefer full-Unicode cmaps to BMP-only ones
  libass/ass_font.c
Labels: compatibility, fonts
